#!/bin/bash

cd /tmp/rom

# Normal build
. build/envsetup.sh
lunch fluid_certus-userdebug
export SELINUX_IGNORE_NEVERALLOWS=true

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	make api-stubs-docs
	make system-api-stubs-docs
	make test-api-stubs-docs
}

make_rom(){
	make bacon -j16
	zip=$(up out/target/product/certus/*zip)
	echo " "
	echo "$zip"
}

make_metalava
make_rom
echo "Build Completed . . ."
